- name: Get Switchover Target Database Name
  set_fact:
     switchover_target_database_name: "{{ database_primary_sid | default(database_standby_sid) }}"

- name: Check Ready for Switchover
  import_tasks: check_readiness.yml

- name: Run Switchover
  import_tasks: switchover.yml
  when: action | default('Check Readiness') != 'Check Readiness'
